### PR TITLE
Add option to list auto-build queue

### PR DESCRIPTION
**Pull request by avoinea**
A missing, but a very useful Docker Hub feature.

You can test it over the `plone` org.
```
bin/docker-hub queue --orgname plone
```

### CODE REVIEW

**Comment by amalfra** [comment]
@avoinea thanks for opening PR, appreciate for your time. This is really very useful feature.
Isn't it better for queue command to accept repo option which will decide which repo's build history to fetch? Now it seems to be fetching all the repos in org and then fetching history for each. isn't it better to allow user to decide which repo's history to fetch?

**Comment by avoinea** [comment]
@amalfra it's coming ;)

It was late last night, and I really needed to see what's blocking my builds as we have `166` auto-build repos, imagine the blindness and the amount of frustration.

I have a lot of other improvement ideas, but I will add then to the issues.

**Comment by amalfra** [comment]
Sounds great! np, take your time... You can ignore the per_page option. I have plan to add per_page as an option(like org, repos, page etc) in future release so that on any supported methods users can configure it

**Comment by avoinea** [comment]
Done
```
docker-hub queue --orgname plone --reponame zeoserver --all
```

**Comment by amalfra** [comment]
@avoinea Thanks for making the changes. A thought I had, queue will basically return build history without status completed. If --all is passed it will return completed build too. so can't we name the command to something like ```buildhistory``` which makes more sense when used with --all? or why don't we do something like ```buildhistory``` will return everything irrespective of status, and user can pass statuses to filter as another param? don't know whether buildhistory api supports filtering by status to do that...

let me know if it's better if not we can release with queue command itself. The idea of this cli tool was that it should be exactly like docker hub, so that anyone familiar with docker hub UI can easily use this. So if commands are same as docker hub tabs it will be much easier for people to use this without much mapping required. It's just my thought by the way, would love to hear your opinion too.. after all it's just about how most people find it easy to use :)

**Comment by avoinea** [comment]
@amalfra 
Indeed, I think `builds` is a better command to see builds history. (same as DockerHub UI URL https://hub.docker.com/r/plone/plone.oauth/builds/)

Thus, I'll leave `queue` as before, and add the new `builds` command.

**Review by amalfra — APPROVED** [review]

**Pull request merged**
